name = "hono-zod-drizzle"
main = "src/index.ts"
compatibility_date = "2024-12-21"

[[d1_databases]]
binding = "DB"
database_name = "stock-trade-db"
database_id = "15cb53ba-8e5c-4497-b44d-821d93a1ef0d"
migrations_dir = "drizzle/migrations"
